sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6.6.0'
before_install:
  - npm i -g npm
services: 
  - mongodb
before_script:
  - npm prune
script:
  - mongod
  - npm run test
  # - npm run coverage